export const releases = [
  {
    version: "1.5",
    date: "june 2026",
    title: "rich export & code-block click fix",
    badge: "feature",
    features: [
      "export a note to pdf or image with a dedicated dialog — pick font, text size, page size and orientation, background, margins, and render quality",
      "markdown is rendered to a real formatted document: headings, lists, tables, blockquotes, and syntax-highlighted code blocks",
      "fixed the text on the line directly above a collapsed code block being hard to click",
    ],
  },
  {
    version: "1.4.2",
    date: "may 2026",
    title: "file properties & collapsible code blocks",
    badge: "feature",
    features: [
      "added a properties panel — right-click any file or folder to see its full path, created and last-updated timestamps, owner, and quick stats (word/character/line counts for files, file and folder counts for folders)",
      "fenced code blocks now collapse to a compact one-line card showing the language, line count and a copy button — they open for editing when you click in, and re-collapse once the cursor leaves",
      "notes now open with every code block collapsed, keeping long notes tidy",
    ],
  },
  {
    version: "1.4.1",
    date: "may 2026",
    title: "smarter file creation & manual sync",
    badge: "patch",
    features: [
      "new files and folders are now created inside the focused folder (or the focused file's parent) — vscode-style — instead of always landing at the root",
      "added a \"sync now\" button in the title bar to pull changes from other devices on demand",
      "fixed background sync writing updates to local storage without refreshing the open view — edits made on another device now appear without signing out and back in",
    ],
  },
  {
    version: "1.4",
    date: "may 2026",
    title: "live formatting & the editor toolbar",
    badge: "feature",
    features: [
      "added a persistent formatting toolbar — pinned to the bottom of the editor",
      "bold, italic and inline-code markers are now concealed as you type",
      "fenced code blocks render as a styled container with the language shown in a small header",
      "find & replace (ctrl+f) is now reachable on mobile straight from the toolbar — no hardware keyboard required",
      "retired the floating selection popover on desktop in favour of the always-visible toolbar and keyboard shortcuts",
    ],
  },
  {
    version: "1.3.1",
    date: "may 2026",
    title: "changelog & save reliability",
    badge: "patch",
    features: [
      "rebuilt changelog as a commit-style timeline so it blends with the rest of the app instead of looking like a separate page",
      "edits are now written to on-device storage as you type — switching notes or closing a note mid-edit no longer loses anything",
      "leaving a note now flushes a final save to the server instead of relying solely on the editor losing focus",
      "save failures from a flaky connection now retry through the offline queue instead of silently stalling on \"saving\"",
      "fixed the changelog page being unable to scroll",
    ],
  },
  {
    version: "1.3",
    date: "may 2026",
    title: "three-way merge for conflicts",
    badge: "feature",
    features: [
      "editing the same note on two devices no longer forces an all-or-nothing choice — non-overlapping changes now merge automatically",
      "genuine overlaps open a side-by-side merge view: resolve each conflict by editing directly or pulling in the other version, then save",
      "the last synced version of every note is kept on-device as a merge base, giving conflict resolution a true common ancestor",
    ],
  },
  {
    version: "1.2.2",
    date: "may 2026",
    title: "mobile fix",
    badge: "patch",
    features: [
      "removed formatting toolbar behind native menu in mobile",
      "fix mobile scroll jumps"
    ],
  },
  {
    version: "1.2.1",
    date: "may 2026",
    title: "instant note switching",
    badge: "patch",
    features: [
      "fixed note switching triggering a server round-trip on every click — opening a note is now fully client-side and instant, matching the offline experience",
    ],
  },
  {
    version: "1.2",
    date: "may 2026",
    title: "local-first storage",
    badge: "feature",
    features: [
      "notes are now cached on-device — opening any note is instant, with no loading spinner or network wait",
      "edits save locally first and sync to the server in the background; nothing is lost if you drop offline mid-edit",
      "fresh devices show a brief loading screen on first launch while notes sync down",
      "edits made on another device are picked up automatically; genuine conflicts still prompt you to choose which version to keep",
      "deletions now propagate reliably across devices",
    ],
  },
  {
    version: "1.1.1",
    date: "may 2026",
    title: "performance & mobile polish",
    badge: "patch",
    features: [
      "removed the sluggish refresh after sidebar operations — rename, move, delete, and create now finish as soon as the server responds",
      "fixed a tab key bug where selecting text within a single line and pressing tab would replace the selection; it now indents the line instead",
      "disabled the custom formatting toolbar on touch devices — it was overlapping the native selection menu",
      "tuned mobile scroll behavior so tapping and selecting text no longer triggers unexpected page jumps",
    ],
  },
  {
    version: "1.1",
    date: "may 2026",
    title: "editor power-ups & ux polish",
    badge: "feature",
    features: [
      "auto-indent on enter — new lines inherit the previous line's indentation",
      "tab now jumps to the next tab stop when typing; still indents the whole block when multiple lines are selected",
      "new integrated shortcut, click (?) icon",
      "inline loading indicators on rename, delete, move, and create — affected items dim and show a spinner",
      "fixed mobile bug where the title bar could scroll off-screen after opening the keyboard on a long note",
    ],
  },
  {
    version: "1.0.3",
    date: "may 2026",
    title: "editor polish & mobile optimization",
    badge: "patch",
    features: [
      "added a floating formatting toolbar for quick styling and code block insertion",
      "improved mobile typing experience with centered cursor and dynamic viewport sizing",
    ],
  },
  {
    version: "1.0.2",
    date: "may 2026",
    title: "editor enhancements & ui polish",
    badge: "patch",
    features: [
      "added collapsible paragraphs and functions in editor",
      "improved tab and indentation spacing",
      "differentiated file and folder visuals in sidebar",
      "added social links in about menu",
    ],
  },
  {
    version: "1.0.1",
    date: "may 2026",
    title: "minor bug fixing",
    badge: "patch",
    features: ["fix minor bugs", "fix manifest.json"],
  },
  {
    version: "1.0",
    date: "may 2026",
    title: "initial release",
    badge: "launch",
    features: [
      "minimalist markdown editor",
      "pwa support for mobile installs",
      "offline-first architecture",
    ],
  },
];
